//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EgyptianGerman.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewReceipt
    {
        public int SercialNo { get; set; }
        public System.DateTime creatationDate { get; set; }
        public string Name { get; set; }
        public double Total { get; set; }
        public double Price { get; set; }
        public int productID { get; set; }
        public string paymentMethod { get; set; }
        public int Quntity { get; set; }
        public string Cname { get; set; }
        public bool Discount { get; set; }
    }
}
